global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dotnet_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['111.111.1.11:5000']
  
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]